[project]
name = "conversationalparadigms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-chroma>=1.1.0",
    "langchain-huggingface>=1.2.2",
    "langchain-ollama>=1.1.0",
    "langchain-text-splitters>=1.1.2",
    "nltk>=3.10.3",
    "pymupdf>=1.28.2",
    "sentence-transformers>=6.1.0",
]
