[project]
name = "conversationalparadigms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crawl4ai>=0.9.4",
    "langchain-chroma>=1.1.0",
    "langchain-huggingface>=1.2.2",
    "langchain-ollama>=1.1.0",
    "langchain-text-splitters>=1.1.2",
    "mcp[cli]>=2.3.0",
    "nltk>=3.10.3",
    "openai>=3.19.2",
    "pymupdf>=1.28.2",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.1",
    "sentence-transformers>=6.1.0",
]
